version: "3.3"
services:
  db:
    container_name: mysqldb
    image: mysql/mysql-server:8.0.23
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Doubledragon40New
      MYSQL_DATABASE: rpgPhobos8
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./mysql-data/8.0.23:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-mysql
    links:
      - db
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
    expose:
      - 8080
